### ISSUE TITLE
use it as installation media source?

### ISSUE THREAD

**Issue by bam80** [jwmullally/dracut-iscsi-target#1]
Just an idea: https://github.com/netbootxyz/netboot.xyz/issues/574#issuecomment-585463658

**Comment by jwmullally** [comment]
Hi, that looks like a nice project. These might be a useful references for netbooting the official LiveCD media:

 https://fedoramagazine.org/netboot-a-fedora-live-cd/
https://lukas.zapletalovi.com/2016/08/hidden-feature-of-fedora-24-live-pxe-boot.html

Closing as the project goals are different (this is about netbooting existing desktop installs). Thanks!
